# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: none

# Setup
title: "MAy 30, 1969
publisher: "National Archeological Anthropological Memorymanagement"
description: "A combination of educational material"

# MOCK
url: ""
baseurl: "/"
future: True
incremental: False

githuburl: 


# Collections
collections:
  issue01:
    slug: issue01
    slug_fr: fr/issue01
    slug_es: es/issue01
    output: true
    number: 1
    date: "May 2022"
    title: "HUMA; LANTAMENTU ANUNSIA"
    editors:
      - Nifa Ansano
      - Tesseley Jansen
      - Dimitri Cloose
    production:
      - Nifa Ansano
      - Dimitri Cloose
      - Angelique Meyer
  issue02:
    slug: issue02
    slug_fr: fr/issue02
    slug_es: es/issue02
    output: true
    number: 2
    date: "MAY 2025"
    title: "Issue (2)"
    editors:
      - Nifa Ansano
      - Dimitri Cloose
    production:
      - Nifa Ansano
      - Kristine Krolis
      - Tesseley Jansen
  issue03:
    slug: issue03
    slug_fr: fr/issue03
    slug_es: es/issue03
    output: true
    number: 3
    date: "April 2019"
    title: "Issue (3)"
    editors:
      - Kaiama Glover
      - Alex Gil
      - Jessica Marie Johnson
    production:
      - Alex Gil
      - Brian Ballsun-Stanton
      - Kelly S. Martin
 

# Current issue
current: issue06
current-number: 6

# Jekyll-Kramdown
markdown: kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Gems
plugins:
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin

# About/contact
author:
  name: "Archipelagos"
  email: info@naam.cw

#i18n
languages: ["en", "es", "fr"]
exclude_from_localizations: []

# Custom vars
version: 0.0.1

# Excluded

exclude:
  [
    Dockerfile,
    docker-readme.txt,
    utility,
    Gemfile,
    Gemfile.lock,
    extras,
    vendor,
    RAKEFILE,
    update.log,
    _issue01,
    _issue02,
    _issue03,
    _issue04,
    _issue05,
    _issue06,
    todo,
  ]
